branch-defaults:
  master:
    environment: pagamento-env
    group_suffix: null
environment-defaults:
  pagamento-env:
    branch: master
    repository: pagamento
global:
  application_name: pagamento
  branch: master
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: LabInstanceProfile
  platform_name: null
  platform_version: null
  profile: null
  repository: pagamento
  sc: git
  workspace_type: Application
  
  
